# Generated by Django 3.2.6 on 2021-09-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinstance',
            old_name='details',
            new_name='imprint',
        ),
    ]
