# Generated by Django 3.2.6 on 2021-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0002_rename_details_carinstance_imprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_owner', models.CharField(help_text='Please enter your name', max_length=200, verbose_name='Name')),
            ],
        ),
    ]
