# Generated by Django 3.2.6 on 2021-09-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0003_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car'),
        ),
        migrations.AddField(
            model_name='carowner',
            name='information',
            field=models.TextField(help_text='Some additonal information about you', max_length=1000, null=True),
        ),
    ]
