# Generated by Django 3.2.6 on 2021-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_auto_20210926_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image_one',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
