# Generated by Django 3.2.6 on 2021-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0006_carowner_image_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='car_owner',
        ),
        migrations.AddField(
            model_name='carowner',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(help_text='Please enter your Firstname', max_length=200, null=True, verbose_name='Firstame'),
        ),
        migrations.AddField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(help_text='Please enter your Lastname', max_length=200, null=True, verbose_name='Lastame'),
        ),
    ]
