# Generated by Django 3.2.6 on 2021-09-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0007_auto_20210929_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_one',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Car Picture'),
        ),
    ]
